Repository The-Unleashed-Club/LinkedInRestApi, pull requests merged in 2023-04, with the labels that each got.

#7 authentication-ui #3
  src/App.js
  src/assets/Vector.png
  src/components/Footer.js
  src/components/Login.js
  src/components/footer.scss
  src/components/login.scss
Labels: UI

#8 sass error
  package.json
Labels: bug

#11 Portfolio UI element
  package-lock.json
  package.json
  src/App.js
  src/assets/data/portfolio_data.jsx
  src/assets/images/img1.png
  src/assets/images/img10.png
  src/assets/images/img11.png
  src/assets/images/img12.png
  src/assets/images/img13.png
  src/assets/images/img14.png
  src/assets/images/img15.png
  src/assets/images/img16.png
  src/assets/images/img17.png
  src/assets/images/img18.png
  src/assets/images/img19.png
  src/assets/images/img2.png
  src/assets/images/img3.png
  src/assets/images/img4.png
  src/assets/images/img5.png
  src/assets/images/img6.png
  src/assets/images/img7.png
  src/assets/images/img8.png
  src/assets/images/img9.png
  src/components/CardItem.jsx
  src/components/Login.js
  src/components/Loginpage.jsx
  src/components/login.scss
  src/pages/Portfolio.jsx
  src/styling/cardItem.css
  src/styling/portfolio.css
Labels: enhancement, UI
